
services:
  db:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - my_network

  fastapi:
    build: .
    container_name: fastapi_user
    depends_on:
      - db
    image: fastapi_user
    ports:
      - "8085:8085"
    environment:
      DB_URL: mysql+mysqldb://admin:admin123@db:3306/usermanagement
    volumes:
      - .:/app
    networks:
      - my_network

volumes:
  mysql_data:

networks:
  my_network:
    driver: bridge
