
services:
  db:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  fastapi:
    build: .
    container_name: fastapi
    depends_on:
      - db
    ports:
      - "8000:8000"
    environment:
      DB_URL: mysql+mysqldb://admin:admin123@db:3306/usermanagement
    volumes:
      - .:/app

volumes:
  mysql_data:
